//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaMindSolutionPractical
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaMindDBEntities : DbContext
    {
        public MegaMindDBEntities()
            : base("name=MegaMindDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCity> tblCities { get; set; }
        public DbSet<tblState> tblStates { get; set; }
        public DbSet<tblUserRegistration> tblUserRegistrations { get; set; }
    }
}
