//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaMindSolutionPractical
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        public tblCity()
        {
            this.tblUserRegistrations = new HashSet<tblUserRegistration>();
        }
    
        public long CityID { get; set; }
        public Nullable<long> StateID { get; set; }
        public string CityName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblState tblState { get; set; }
        public virtual ICollection<tblUserRegistration> tblUserRegistrations { get; set; }
    }
}
