//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaMindSolutionPractical
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public tblState()
        {
            this.tblCities = new HashSet<tblCity>();
            this.tblUserRegistrations = new HashSet<tblUserRegistration>();
        }
    
        public long StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<tblCity> tblCities { get; set; }
        public virtual ICollection<tblUserRegistration> tblUserRegistrations { get; set; }
    }
}
